### ISSUE TITLE
麻烦帮我看看，我搞了2天都写不正确。

### ISSUE THREAD

**Issue by klsdfjo** [imba97/picgo-plugin-ftp-uploader#16]
配置文件这样写，但是提示ftp错误。请问应该怎么写？

{
    "jackwong": {
      "url": "https://xxxxx:5543",
      "path": "/uploads/{year}/{month}/{fullName}",
      "uploadPath": "/图床/uploads/{year}/{month}/{fullName}",
      "host": "xxx",
      "port": 5542,
      "username": "***",
      "password": "***"
    }
}

**Comment by imba97** [comment]
picgo的配置是怎么写的

**Comment by klsdfjo** [comment]
你好，我已收到你的e-mail，谢谢。

**Comment by klsdfjo** [comment]
> 

我快奔溃了，今天第三天了，还是不行。我还在查资料，好像查不到

**Comment by klsdfjo** [comment]
> picgo的配置是怎么写的
1.正常安装好picgo客户端，然后安装ftp upload插件。
2.ftp upload配置：
网站标识：jackwong
配置文件：‪D:\ftpUploaderConfig.json
（文件在D盘，文件名字叫ftpUploaderConfig.json）

**Comment by klsdfjo** [comment]
> 你好，我也是这个问题，请问怎么解决的呢？
我快奔溃了，今天第三天了，还是不行。我还在查资料，好像查不到

**Comment by klsdfjo** [comment]
> picgo的配置是怎么写的

Error: ENOENT: no such file or directory, open '‪D:\ftpUploaderConfig.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at C:\Users\pc\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:73:45
    at new Promise (<anonymous>)
    at Object.exports.getFtpConfig (C:\Users\pc\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:38:12)
    at Object.handle (C:\Users\pc\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:12:43)
-------Error Stack End-------

**Comment by imba97** [comment]
报错是没找到 `D:\ftpUploaderConfig.json`
你试试把反斜杠换成斜杠试试 `D:/ftpUploaderConfig.json`

**Comment by klsdfjo** [comment]
> 

还是不行哦哥。可以加微信指导一下吗。快奔溃。我的ftp能正常访问得。我用其他软件访问ftp也没问题。

**Comment by klsdfjo** [comment]
> 报错是没找到 `D:\ftpUploaderConfig.json` 你试试把反斜杠换成斜杠试试 `D:/ftpUploaderConfig.json`

还是不行哦哥。可以加微信指导一下吗。快奔溃。我的ftp能正常访问得。我用其他软件访问ftp也没问题。

**Comment by klsdfjo** [comment]
> 报错是没找到 `D:\ftpUploaderConfig.json` 你试试把反斜杠换成斜杠试试 `D:/ftpUploaderConfig.json`

VX：3276074

**Comment by klsdfjo** [comment]
> 报错是没找到 `D:\ftpUploaderConfig.json` 你试试把反斜杠换成斜杠试试 `D:/ftpUploaderConfig.json`

感激不尽

**Comment by klsdfjo** [comment]
> 报错是没找到 `D:\ftpUploaderConfig.json` 你试试把反斜杠换成斜杠试试 `D:/ftpUploaderConfig.json`

我把文件拉过去E盘，读取E盘，不行。又拉回来D盘，改为配置为D盘。也不行。我重复了2次，现在可以了。没有改jso代码。竟然现在可以了。百思不得其解。额。。。。

**Comment by imba97** [comment]
可以了就好，V先不加了

**Comment by imba97** [comment]
> 你好，我也是这个问题，请问怎么解决的呢？

看一下配置的路径是不是对的

**Comment by chenzao1024** [comment]
picgo 配置
"ftp-uploader": {
      "configFile": "/Users/tunny/Downloads/picGoConfig.json",
      "site": "echoFamily"
    }

picGoConfig.json 配置
{
  "echoFamily": {
    "url": "https://群晖域名:5544",
    "path": "/uploads/{year}/{month}/{fullName}",
    "uploadPath": "/web/blogImages/uploads/{year}/{month}/{fullName}",
    "host": "群晖域名",
    "port": 5542,
    "username": "xxxx",
    "password": "xxxxxx"
  }
}

报错如下：
2022-03-08 09:12:17 [PicGo INFO] Before transform 
2022-03-08 09:12:17 [PicGo INFO] Transforming... Current transformer is [path] 
2022-03-08 09:12:17 [PicGo INFO] Before upload 
2022-03-08 09:12:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-03-08 09:12:18 [PicGo INFO] Uploading... Current uploader is [ftp-uploader] 
2022-03-08 09:12:18 [PicGo ERROR] FTP 发生错误，请检查配置是否正确 
2022-03-08 09:12:18 [PicGo SUCCESS] 

网络环境：
电信动态公网IP，使用DDNS域名解析，在路由器上进行端口转发到群晖主机（直接使用域名不能访问到群晖主机，需要加上端口号）

猜测问题原因：
host 填写的域名 无法直接找到对应的主机IP地址
请问作者这个有什么办法可以解决吗？
跪谢~。~
