### ISSUE TITLE
配置一直报错是因为什么

### ISSUE THREAD

**Issue by demo112** [imba97/picgo-plugin-ftp-uploader#19]
------Error Stack Begin------
SyntaxError: Unexpected token } in JSON at position 352
    at JSON.parse (<anonymous>)
    at C:\Users\Smbtest\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:73:26
    at new Promise (<anonymous>)
    at Object.exports.getFtpConfig (C:\Users\Smbtest\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:38:12)
    at Object.handle (C:\Users\Smbtest\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:12:43)
    at Lifecycle.doUpload (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:77)
    at Lifecycle.start (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:24)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async PicGo.upload (C:\Program Files (x86)\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (C:\Program Files (x86)\PicGo\resources\app.asar\background.js:36:29196)
配置文件
  "smbtest-ftp": {
    "url": "http://61.164.52.174:8081",
    "path": "/automation-tool-group/automation-tool-bug-tracking-system/uploads/{year}/{month}/{fullName}",
    "uploadPath": "/1个人文件/88图床/{year}/{month}/{fullName}",

**Comment by imba97** [comment]
配置文件内容格式不对，严格按照`json`的格式
