### ISSUE TITLE
单个上传时没事，但是在批量上传时报错

### ISSUE THREAD

**Issue by wzcsimon123** [imba97/picgo-plugin-ftp-uploader#29]
`------Error Stack Begin------
Error: Client is closed because User launched a task while another one is still running. Forgot to use 'await' or '.then()'?
    at C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\FtpContext.js:226:29
    at new Promise (<anonymous>)
    at FTPContext.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\FtpContext.js:208:16)
    at Client._handleConnectResponse (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:92:25)
    at Client.connect (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:76:21)
    at Client.access (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:214:34)
    at Object.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:19:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
Closing reason: Error: User launched a task while another one is still running. Forgot to use 'await' or '.then()'?
    at FTPContext.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\FtpContext.js:201:25)
    at Client._handleConnectResponse (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:92:25)
    at Client.connect (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:76:21)
    at Client.access (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:214:34)
    at Object.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:19:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (E:\PicGo\resources\app.asar\background.js:2:653584)
Running task launched at: Error
    at C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\FtpContext.js:210:24
    at new Promise (<anonymous>)
    at FTPContext.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\FtpContext.js:208:16)
    at Client._handleConnectResponse (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:92:25)
    at Client.connect (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:76:21)
    at Client.access (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\basic-ftp\dist\Client.js:214:34)
    at Object.handle (C:\Users\wzcsi\AppData\Roaming\picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:19:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (E:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
-------Error Stack End------- `

**Comment by imba97** [comment]
你是用什么方式上传的

我这边测试了一下是没啥问题的，直接点上传，多选文件可以正常上传

```
2023-02-13 09:40:14 [PicGo INFO] Before transform 
2023-02-13 09:40:14 [PicGo INFO] Transforming... Current transformer is [path] 
2023-02-13 09:40:14 [PicGo INFO] Before upload 
2023-02-13 09:40:14 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-02-13 09:40:14 [PicGo INFO] Uploading... Current uploader is [ftp-uploader] 
2023-02-13 09:40:18 [PicGo SUCCESS] 
https://test.imba97.cn/uploads/2023/02/Snipaste_2023-02-13_09-38-17.jpg
https://test.imba97.cn/uploads/2023/02/Snipaste_2023-02-13_09-38-12.jpg 
```

剪贴板图片上传也能成功，但只上传了一个，估计是 `PicGo` 只传过来了一个

错确实是插件报的，但没试出来你那个报错

**Comment by wzcsimon123** [comment]
typora 设置网络图片自动上传
粘贴剪贴板图片（网络图床）到typora时报错。

**Comment by Ahellowyy** [comment]
我也是报的同样的错误,

![Image](https://github.com/user-attachments/assets/2b81fb8d-9f34-4026-b858-c80e127c524e)

**Comment by Ahellowyy** [comment]
如果一个文档中有多个图, 都是本地的, 依次点击 "格式"-->"图像"-->"上传所有本地图像"  就会报这个错. 我用的typora版本是1.10.8
