### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by darkmanno6** [imba97/picgo-plugin-ftp-uploader#3]
node版本：16.6.1
运行环境：windows10
执行上传命令
```
picgo upload "C:\\Users\\darkm\\AppData\\Local\\Temp/typora-icon2.png" "C:\\Users\\darkm\\AppData\\Local\\Temp/typora-icon.png"
```
程序运行结果：
```
[PicGo INFO]: Before transform
[PicGo INFO]: Transforming... Current transformer is [path]
[PicGo INFO]: Before upload
[PicGo INFO]: Uploading... Current uploader is [ftp-uploader]
[PicGo WARN]: failed
[PicGo ERROR]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
at Object.openSync (node:fs:574:10)
at Object.readFileSync (node:fs:450:35)
at C:\Users\darkm\.picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:63:45
at new Promise (<anonymous>)
at Object.exports.getFtpConfig (C:\Users\darkm\.picgo\node_modules\picgo-plugin-ftp-uploader\dist\config.js:37:12)
at Object.handle (C:\Users\darkm\.picgo\node_modules\picgo-plugin-ftp-uploader\dist\index.js:12:43)
at Lifecycle.doUpload (C:\Users\darkm\AppData\Roaming\nvm\v16.6.1\node_modules\picgo\dist\src\core\Lifecycle.js:80:77)
at Lifecycle.start (C:\Users\darkm\AppData\Roaming\nvm\v16.6.1\node_modules\picgo\dist\src\core\Lifecycle.js:26:24)
at async PicGo.upload (C:\Users\darkm\AppData\Roaming\nvm\v16.6.1\node_modules\picgo\dist\src\core\PicGo.js:205:32)
at async C:\Users\darkm\AppData\Roaming\nvm\v16.6.1\node_modules\picgo\dist\src\plugins\commander\upload.js:30:17 {
code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by darkmanno6** [comment]
环境：mac+node v14.15.0 也同样报这个错

**Comment by darkmanno6** [comment]
看了下代码，应该是我配置有问题，之前网上看配置的没有单独的配置文件

**Comment by imba97** [comment]
之前更新了一下 现在需要单独的配置文件
