### ISSUE TITLE
一直报错用不了，不知道啥原因

### ISSUE THREAD

**Issue by Sunjay119** [imba97/picgo-plugin-ftp-uploader#30]
2023-04-15 20:07:58 [PicGo ERROR] 
------Error Stack Begin------
Error: [object Object]
    at Object.ve [as handle] (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18794)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:661590)
    at async zn (C:\Users\Sunjay\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:664240)
-------Error Stack End-------

**Comment by imba97** [comment]
这个报错信息好像没看出是插件报的，是使用 FTP 插件就会失败吗

**Comment by Sunjay119** [comment]
是的，用SFTP就没有问题，应该是FTP插件代码的原因

**Comment by imba97** [comment]
试一下新的版本
